
spring:
  datasource:
    url: jdbc:postgresql://192.168.50.3:5432/test_rbac
    username: postgres
    password: yp037629701
    driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update


jwtUtils.jwtSecret: bezKoderSecretKey
jwtUtils.jwtExpirationMs: 86400000